AWSTemplateFormatVersion: 2010-09-09
Description: Serverless Email AI

Resources:
  ExtractEmailLambda:
    Type: AWS::Lambda::Function
    Properties:
      CodeUri: .
      FunctionName: ExtractEmailLambda
      Runtime: nodejs20.x
      Handler: index.handler
      Architectures:
        - x86_64
      Environment:
          Variables:
            NODE_OPTIONS: --enable-source-maps
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: true
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - index.ts
        Banner:
        - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
